name: Create reports
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make
      - uses: EndBug/add-and-commit@v8
        with:
          message: 'Updated via Github Actions workflow'
          push: true
